#!python
from bk_utils import clear
from pprint import pprint as pp
import locale
import json

locale.setlocale(locale.LC_ALL, '')


def load_menu_data_json(filename):
    with open(filename, "r") as f:
        data = json.load(f)
    return data["data"]


def display_menu(menu_items):
    clear()
    print("       MENU\n========================")
    for i in range(0, len(menu_items)):
        print(f'{i + 1}: {menu_items[i]["menu_item"]}')
    print("Q: Quit\n")


def menu():
    menu_items = load_menu_data_json("menu_data.json")
    pp(menu_items)
    for item in menu_items:
        print(f'Executing \"{item["import_command"]}\"...')
        exec(f'{item["import_command"]}')

    while True:
        display_menu(menu_items)
        choice = input("Option: ")
        if choice.lower() == "q":
            clear()
            exit()
        elif int(choice) in range(1, len(menu_items) + 1):
            exec(f'{menu_items[int(choice) - 1]["execution_command"]}')
        else:
            pass


menu()
